name: Get Tag
run-name: Get Previous Tag
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
#       - name: 'Get Previous tag'
#         id: previoustag
#         uses: "WyriHaximus/github-action-get-previous-tag@v1"
#         with:
#           fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#       - name: 'Echo Tag'
#         run: echo "${{ steps.previoustag.outputs.tag }}"on:
on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Echo Tag'
        run: echo "${{ steps.previoustag.outputs.tag }}"
